# Form implementation generated from reading ui file 'diet_dialog.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(221, 95)
        Dialog.setStyleSheet("\n"
"QWidget {\n"
"    font: 11pt \"Helvetica\";\n"
"    border-radius:10px;\n"
"background:#121212;\n"
"}\n"
"\n"
"QFrame {\n"
"background:#121212;\n"
"}\n"
"\n"
"/* ///////////////////////////////////////////////////////////////\n"
"QSpinBox\n"
"/////////////////////////////////////////////////////////////// */\n"
"QSpinBox {color:rgb(143,148,255);}\n"
"QSpinBox:hover {color: rgb(203,208,255);}\n"
"QSpinBox:focus {color: rgb(173,178,255);}\n"
"\n"
"\n"
"/* ////////////////////////////////////////////////////////////////////////////////\n"
"QLabel\n"
"//////////////////////////////////////////////////////////////////////////////// */\n"
"QLabel {\n"
"    background:transparent;\n"
"    color:rgb(143,148,255);\n"
"}\n"
"QLabel:hover {\n"
"    color: rgb(203,208,255);\n"
"}\n"
"\n"
"/* ////////////////////////////////////////////////////////////////////////////////\n"
"QLineEdit\n"
"//////////////////////////////////////////////////////////////////////////////// */\n"
"QLineEdit {    font-size:11pt;\n"
"    border:none;\n"
"    color:rgb(143,148,255);\n"
"}\n"
"\n"
"QLineEdit:hover {\n"
"    color:rgb(173,178,255);\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    color:rgb(123,128,235);\n"
"}\n"
"\n"
"QDateEdit,\n"
"QTimeEdit {    font-size:11pt;\n"
"    border:none;\n"
"    color:rgb(143,148,255);\n"
"}\n"
"\n"
"QDateEdit:hover,\n"
"QTimeEdit:hover {\n"
"    color:rgb(173,178,255);\n"
"}\n"
"\n"
"QDateEdit:focus,\n"
"QTimeEdit:focus {\n"
"    color:rgb(123,128,235);\n"
"}\n"
"/* ////////////////////////////////////////////////////////////////////////////////\n"
"QPushButton\n"
"//////////////////////////////////////////////////////////////////////////////// */\n"
"QPushButton {\n"
"    min-width:65px;\n"
"    border:none;\n"
"    color:rgb(143,148,255);\n"
"}\n"
"QPushButton:hover {\n"
"    color:rgb(173,178,255);\n"
"}\n"
"QPushButton:pressed {\n"
"    color: #666;\n"
"}\n"
"\n"
"QPushButton {\n"
"    color:rgb(123,128,235);\n"
"}\n"
"\n"
"QPushButton:focus {\n"
"    color:#fff;\n"
"}\n"
"\n"
"/* ///////////////////////////////////////////////////////////////\n"
"QSlider Colors\n"
"/////////////////////////////////////////////////////////////// */\n"
"\n"
"QSlider::handle:horizontal {background:rgb(143,148,255);}\n"
"QSlider::handle:horizontal:hover {background:rgb(173,178,255);}\n"
"QSlider::handle:horizontal:pressed {background:rgb(123,128,235);}\n"
"QSlider::groove:horizontal:hover {background:rgba(143,148,255,0.25);}\n"
"QSlider::groove:horizontal {background:rgba(143,148,255,0.15);}\n"
"\n"
"\n"
"\n"
"")
        self.gridLayout = QtWidgets.QGridLayout(Dialog)
        self.gridLayout.setObjectName("gridLayout")
        self.frame = QtWidgets.QFrame(parent=Dialog)
        self.frame.setObjectName("frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout.setObjectName("verticalLayout")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.food_eaten = QtWidgets.QLineEdit(parent=self.frame)
        self.food_eaten.setFrame(False)
        self.food_eaten.setObjectName("food_eaten")
        self.verticalLayout.addWidget(self.food_eaten)
        self.calories = QtWidgets.QSpinBox(parent=self.frame)
        self.calories.setFrame(False)
        self.calories.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.calories.setButtonSymbols(QtWidgets.QAbstractSpinBox.ButtonSymbols.NoButtons)
        self.calories.setMaximum(3000)
        self.calories.setSingleStep(10)
        self.calories.setObjectName("calories")
        self.verticalLayout.addWidget(self.calories)
        self.buttonBox = QtWidgets.QDialogButtonBox(parent=self.frame)
        self.buttonBox.setStyleSheet("QFrame {background: transparent;}\n"
"QPushButton {\n"
"padding:2px;\n"
"color:rgb(45, 45, 88);\n"
"border:1px solid rgb(182, 180, 255);\n"
"background:rgb(182, 180, 255);\n"
"border-radius:3px;\n"
"min-width:40px;\n"
"max-width:40px;\n"
"min-height:13px;\n"
"max-height:13px;\n"
"\n"
"}\n"
"QPushButton:hover {\n"
"margin-top:1px;\n"
"margin-left:1px;\n"
"border:1px solid rgb(145, 150, 255);\n"
"background:rgb(145, 150, 255);\n"
"color: rgb(45, 50, 155);\n"
"font-size:9pt;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"color:#fff;\n"
"    margin-top:0px;\n"
"    margin-left:0px;border:2px solid rgb(145, 150, 255);\n"
"}")
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.No|QtWidgets.QDialogButtonBox.StandardButton.Ok)
        self.buttonBox.setCenterButtons(True)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.gridLayout.addWidget(self.frame, 0, 0, 1, 1)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.food_eaten.setPlaceholderText(_translate("Dialog", "what did I eat?"))
        self.calories.setSuffix(_translate("Dialog", " Calories"))
