# Form implementation generated from reading ui file 'cspr_dialog.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(235, 290)
        Dialog.setStyleSheet("QWidget {\n"
"    font: 11pt \"Helvetica Neue\";\n"
"    background: #161616;\n"
"}\n"
"\n"
"/* /////////////////////////////////////////////////////////////////////////////\n"
"QSlider\n"
"///////////////////////////////////////////////////////////////////////////// */\n"
"QSlider::groove:vertical {\n"
"border-radius: 5px;\n"
"width: 30px;\n"
"margin: 0px;\n"
"background:rgb(22, 24, 29);\n"
"}\n"
"\n"
"QSlider::groove:vertical:hover {\n"
"background: rgba(233,123,111,0.25);\n"
"}\n"
"\n"
"QSlider::handle:vertical {\n"
"background: rgb(233,123,111);\n"
"height: 25px;\n"
"width: 40px;\n"
"margin: 0px -9px 0px -9px;\n"
"border-radius:5px;\n"
"}\n"
"\n"
"QSlider::add-page:vertical {\n"
"background:transparent;\n"
"}\n"
"\n"
"QSlider::handle:vertical:hover {\n"
"background-color: rgb(255,163,151);\n"
"}\n"
"\n"
"QSlider::handle:vertical:pressed {\n"
"background-color:rgb(188,78,66);\n"
"}\n"
"\n"
"\n"
"\n"
"\n"
"/* ///////////////////////////////////////////////////////////////\n"
"WEFE SLIDERS\n"
"/////////////////////////////////////////////////////////////// */\n"
"\n"
"#wellbeing_slider::handle:vertical {background:rgb(142,150,255);}\n"
"#wellbeing_slider::handle:vertical:hover {background:rgb(182,190,255);}\n"
"#wellbeing_slider::handle:vertical:pressed {background:rgb(92,100,205);}\n"
"#wellbeing_slider::groove:vertical:hover {background:rgba(142,150,255,0.25);}\n"
"#wellbeing_slider::groove:vertical {background:rgba(142,150,255,0.15);}\n"
"\n"
"        \n"
"\n"
"/* ///////////////////////////////////////////////////////////////\n"
"QSlider Colors\n"
"/////////////////////////////////////////////////////////////// */\n"
"\n"
"#energy_slider::handle:vertical {background:rgb(64,68,132);}\n"
"#energy_slider::handle:vertical:hover {background:rgb(104,108,172);}\n"
"#energy_slider::handle:vertical:pressed {background:rgb(44,58,122);}\n"
"#energy_slider::groove:vertical:hover {background:rgba(64,68,132,0.25);}\n"
"#energy_slider::groove:vertical {background:rgba(64,68,132,0.15);}\n"
"\n"
"        \n"
"\n"
"/* ///////////////////////////////////////////////////////////////\n"
"QSlider Colors\n"
"/////////////////////////////////////////////////////////////// */\n"
"\n"
"#excite_slider::handle:vertical {\n"
"    background:rgb(113,119,203);\n"
"}\n"
"#excite_slider::handle:vertical:hover {\n"
"    background:rgb(153,159,243);\n"
"}\n"
"#excite_slider::handle:vertical:pressed {\n"
"    background:rgb(64,68,132);\n"
"}\n"
"#excite_slider::groove:vertical:hover {\n"
"    background:rgba(113,119,203,0.25);\n"
"}\n"
"#excite_slider::groove:vertical {    \n"
"    background:rgba(113,119,203,0.15);\n"
"}\n"
"\n"
"#focus_slider::handle:vertical {background:rgb(87,90,156);}\n"
"#focus_slider::handle:vertical:hover {background:rgb(127,130,196);}\n"
"#focus_slider::handle:vertical:pressed {background:rgb(64,68,132);}\n"
"#focus_slider::groove:vertical:hover {background:rgba(87,90,156,0.25);}\n"
"#focus_slider::groove:vertical {background:rgba(87,90,156,0.15);}\n"
"\n"
"        \n"
"\n"
"\n"
"/* ///////////////////////////////////////////////////////////////\n"
"CSPR\n"
"/////////////////////////////////////////////////////////////// */\n"
"\n"
"#calm_slider::handle:vertical {background:rgb(52,121,71);}\n"
"#calm_slider::handle:vertical:hover {background:rgb(92,161,111);}\n"
"#calm_slider::handle:vertical:pressed {background:rgb(32,100,51);}\n"
"#calm_slider::groove:vertical:hover {background:rgba(52,121,71,0.25);}\n"
"#calm_slider::groove:vertical {background:rgba(52,121,71,0.15);}\n"
"\n"
"#stress_slider::handle:vertical {background:rgb(77,176,104);}\n"
"#stress_slider::handle:vertical:hover {background:rgb(117,216,144);}\n"
"#stress_slider::handle:vertical:pressed {background:rgb(52,121,71);}\n"
"#stress_slider::groove:vertical:hover {background:rgba(77,176,104,0.25);}\n"
"#stress_slider::groove:vertical {background:rgba(77,176,104,0.15);}\n"
"\n"
"        \n"
"#pain_slider::handle:vertical {background:rgb(90,207,122);}\n"
"#pain_slider::handle:vertical:hover {background:rgb(130,247,162);}\n"
"#pain_slider::handle:vertical:pressed {background:rgb(52,121,71);}\n"
"#pain_slider::groove:vertical:hover {background:rgba(90,207,122,0.25);}\n"
"#pain_slider::groove:vertical {background:rgba(90,207,122,0.15);}\n"
"\n"
"#rage_slider::handle:vertical {background:rgb(123,241,155);}\n"
"#rage_slider::handle:vertical:hover {background:rgb(163,255,195);}\n"
"#rage_slider::handle:vertical:pressed  {background:rgb(52,121,71);}\n"
"#rage_slider::groove:vertical:hover {background:rgba(123,241,155,0.25);}\n"
"#rage_slider::groove:vertical {background:rgba(123,241,155,0.15);}\n"
"\n"
"        \n"
"\n"
"/* ///////////////////////////////////////////////////////////////\n"
"MMDMR\n"
"/////////////////////////////////////////////////////////////// */\n"
"#mood_slider::handle:vertical {background:rgb(109,92,128);}\n"
"#mood_slider::handle:vertical:hover {background:rgb(149,132,168);}\n"
"#mood_slider::handle:vertical:pressed {background:rgb(89,72,100);}\n"
"#mood_slider::groove:vertical:hover {background:rgba(109,92,128,0.25);}\n"
"#mood_slider::groove:vertical {background:rgba(109,92,128,0.15);}\n"
"\n"
"#mania_slider::handle:vertical {background:rgb(135,114,159);}\n"
"#mania_slider::handle:vertical:hover {background:rgb(175,154,199);}\n"
"#mania_slider::handle:vertical:pressed {background:rgb(109,92,128);}\n"
"#mania_slider::groove:vertical:hover {background:rgba(135,114,159,0.25);}\n"
"#mania_slider::groove:vertical {background:rgba(135,114,159,0.15);}\n"
"\n"
"#depression_slider::handle:vertical {background:rgb(174,146,204);}\n"
"#depression_slider::handle:vertical:hover {background:rgb(214,186,244);}\n"
"#depression_slider::handle:vertical:pressed {background:rgb(109,92,128);}\n"
"#depression_slider::groove:vertical:hover {background:rgba(174,146,204,0.25);}\n"
"#depression_slider::groove:vertical {background:rgba(174,146,204,0.15);}\n"
"\n"
"#mixed_risk_slider::handle:vertical {background:rgb(211,191,232);}\n"
"#mixed_risk_slider::handle:vertical:hover {background:rgb(251,231,255);}\n"
"#mixed_risk_slider::handle:vertical:pressed {background:rgb(109,92,128);}\n"
"#mixed_risk_slider::groove:vertical:hover {background:rgba(211,191,232,0.25);}\n"
"#mixed_risk_slider::groove:vertical {background:rgba(211,191,232,0.15);}\n"
"\n"
"        \n"
"        \n"
"/*\n"
"QSpinBoxes\n"
"*/\n"
"\n"
"/*CSPR*/\n"
"#calm_spinbox {color:rgb(52,121,71);}\n"
"#calm_spinbox:hover {color: rgb(112,181,131);}\n"
"#calm_spinbox:focus {color: rgb(82,151,101);}\n"
"\n"
"#stress_spinbox {color:rgb(73,167,98);}\n"
"#stress_spinbox:hover {color: rgb(133,227,158);}\n"
"#stress_spinbox:focus {color: rgb(103,197,128);}\n"
"\n"
"#pain_spinbox{color:rgb(90,208,122);}\n"
"#pain_spinbox:hover {color: rgb(150,255,182);}\n"
"#pain_spinbox:focus {color: rgb(120,238,152);}\n"
"\n"
"#rage_spinbox {color:rgb(123,241,155);}\n"
"#rage_spinbox:hover {color: rgb(183,255,215);}\n"
"#rage_spinbox:focus {color: rgb(153,255,185);}    \n"
"\n"
"/*WEFE*/\n"
"#excite_spinbox{color:rgb(96,103,171);}\n"
"#excite_spinbox:hover {color: rgb(156,163,231);}\n"
"#excite_spinbox:focus {color: rgb(126,133,201);}\n"
"  \n"
"#wellbeing_spinbox {color:rgb(96,103,171);}\n"
"#wellbeing_spinbox:hover {color: rgb(156,163,231);}\n"
"#wellbeing_spinbox:focus {color: rgb(126,133,201);}\n"
"\n"
"#focus_spinbox {color:rgb(96,103,171);}\n"
"#focus_spinbox:hover {color: rgb(156,163,231);}\n"
"#focus_spinbox:focus {color: rgb(126,133,201);}\n"
"\n"
"#energy_spinbox {color:rgb(96,103,171);}\n"
"#energy_spinbox:hover {color: rgb(156,163,231);}\n"
"#energy_spinbox:focus {color: rgb(126,133,201);}\n"
"\n"
"/*MMDMR*/\n"
"#mood {color:rgb(109,92,128);}\n"
"#mood:hover {color: rgb(169,152,188);}\n"
"#mood:focus {color: rgb(139,122,158);}\n"
"\n"
"#mania {color:rgb(135,114,159);}\n"
"#mania:hover {color: rgb(195,174,219);}\n"
"#mania:focus {color: rgb(165,144,189);}\n"
"    \n"
"#depression {color:rgb(174,146,204);}\n"
"#depression:hover {color: rgb(234,206,255);}\n"
"#depression:focus {color: rgb(204,176,234);}\n"
"    \n"
"\n"
"#mixed_risk {color:rgb(211,191,232);}\n"
"#mixed_risk:hover {color: rgb(255,251,255);}\n"
"#mixed_risk:focus {color: rgb(241,221,255);}")
        self.gridLayout = QtWidgets.QGridLayout(Dialog)
        self.gridLayout.setObjectName("gridLayout")
        self.csprContainer = QtWidgets.QFrame(parent=Dialog)
        self.csprContainer.setStyleSheet("QSpinBox {\n"
"background:transparent;\n"
"border:none;\n"
"}")
        self.csprContainer.setObjectName("csprContainer")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.csprContainer)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.frame = QtWidgets.QFrame(parent=self.csprContainer)
        self.frame.setObjectName("frame")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.frame)
        self.gridLayout_2.setContentsMargins(0, 8, 0, 0)
        self.gridLayout_2.setHorizontalSpacing(0)
        self.gridLayout_2.setVerticalSpacing(8)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.rage_slider = QtWidgets.QSlider(parent=self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rage_slider.sizePolicy().hasHeightForWidth())
        self.rage_slider.setSizePolicy(sizePolicy)
        self.rage_slider.setStatusTip("")
        self.rage_slider.setStyleSheet("\n"
"    /* ///////////////////////////////////////////////////////////////\n"
"    QToolTip\n"
"    /////////////////////////////////////////////////////////////// */\n"
"    QToolTip {\n"
"        background: rgba(23,23,23, 150);\n"
"        border: 1px solid rgb(52,121,71);\n"
"        border-radius: 5px;\n"
"        padding:4px;\n"
"        text-align: left;\n"
"        color: rgb(52,121,71);\n"
"    }\n"
"    \n"
"\n"
"        QSlider::handle:vertical:hover {\n"
"image:url(:/newPrefix/ragehomie.png);\n"
"}")
        self.rage_slider.setMaximum(10)
        self.rage_slider.setObjectName("rage_slider")
        self.gridLayout_2.addWidget(self.rage_slider, 1, 3, 1, 1)
        self.calm_slider = QtWidgets.QSlider(parent=self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.calm_slider.sizePolicy().hasHeightForWidth())
        self.calm_slider.setSizePolicy(sizePolicy)
        self.calm_slider.setStatusTip("")
        self.calm_slider.setStyleSheet("\n"
"    /* ///////////////////////////////////////////////////////////////\n"
"    QToolTip\n"
"    /////////////////////////////////////////////////////////////// */\n"
"    QToolTip {\n"
"        background: rgba(23,23,23, 150);\n"
"        border: 1px solid rgb(52,121,71);\n"
"        border-radius: 5px;\n"
"        padding:4px;\n"
"        text-align: left;\n"
"        color: rgb(52,121,71);\n"
"    }\n"
"    \n"
"\n"
"        QSlider::handle:vertical:hover {\n"
"image:url(:/newPrefix/calmhomie.png);\n"
"}")
        self.calm_slider.setMaximum(10)
        self.calm_slider.setInvertedAppearance(False)
        self.calm_slider.setInvertedControls(False)
        self.calm_slider.setTickPosition(QtWidgets.QSlider.TickPosition.NoTicks)
        self.calm_slider.setObjectName("calm_slider")
        self.gridLayout_2.addWidget(self.calm_slider, 1, 0, 1, 1)
        self.calm_spinbox = QtWidgets.QSpinBox(parent=self.frame)
        self.calm_spinbox.setAutoFillBackground(False)
        self.calm_spinbox.setStyleSheet("\n"
"    /* ///////////////////////////////////////////////////////////////\n"
"    QToolTip\n"
"    /////////////////////////////////////////////////////////////// */\n"
"    QToolTip {\n"
"        background: rgba(23,23,23, 150);\n"
"        border: 1px solid rgb(52,121,71);\n"
"        border-radius: 5px;\n"
"        padding:4px;\n"
"        text-align: left;\n"
"        color: rgb(52,121,71);\n"
"    }\n"
"")
        self.calm_spinbox.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.calm_spinbox.setButtonSymbols(QtWidgets.QAbstractSpinBox.ButtonSymbols.NoButtons)
        self.calm_spinbox.setMaximum(10)
        self.calm_spinbox.setObjectName("calm_spinbox")
        self.gridLayout_2.addWidget(self.calm_spinbox, 0, 0, 1, 1)
        self.stress_spinbox = QtWidgets.QSpinBox(parent=self.frame)
        self.stress_spinbox.setAutoFillBackground(False)
        self.stress_spinbox.setStyleSheet("\n"
"    /* ///////////////////////////////////////////////////////////////\n"
"    QToolTip\n"
"    /////////////////////////////////////////////////////////////// */\n"
"    QToolTip {\n"
"        background: rgba(23,23,23, 150);\n"
"        border: 1px solid rgb(73,167,98);\n"
"        border-radius: 5px;\n"
"        padding:4px;\n"
"        text-align: left;\n"
"        color: rgb(73,167,98);\n"
"    }\n"
"\n"
"    ")
        self.stress_spinbox.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.stress_spinbox.setButtonSymbols(QtWidgets.QAbstractSpinBox.ButtonSymbols.NoButtons)
        self.stress_spinbox.setAccelerated(True)
        self.stress_spinbox.setMaximum(10)
        self.stress_spinbox.setObjectName("stress_spinbox")
        self.gridLayout_2.addWidget(self.stress_spinbox, 0, 1, 1, 1)
        self.rage_spinbox = QtWidgets.QSpinBox(parent=self.frame)
        self.rage_spinbox.setAutoFillBackground(False)
        self.rage_spinbox.setStyleSheet("\n"
"    /* ///////////////////////////////////////////////////////////////\n"
"    QToolTip\n"
"    /////////////////////////////////////////////////////////////// */\n"
"    QToolTip {\n"
"        background: rgba(23,23,23, 150);\n"
"        border: 1px solid rgb(123,241,155);\n"
"        border-radius: 5px;\n"
"        padding:4px;\n"
"        text-align: left;\n"
"        color: rgb(123,241,155);\n"
"    }\n"
"")
        self.rage_spinbox.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.rage_spinbox.setButtonSymbols(QtWidgets.QAbstractSpinBox.ButtonSymbols.NoButtons)
        self.rage_spinbox.setMaximum(10)
        self.rage_spinbox.setObjectName("rage_spinbox")
        self.gridLayout_2.addWidget(self.rage_spinbox, 0, 3, 1, 1)
        self.stress_slider = QtWidgets.QSlider(parent=self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stress_slider.sizePolicy().hasHeightForWidth())
        self.stress_slider.setSizePolicy(sizePolicy)
        self.stress_slider.setStatusTip("")
        self.stress_slider.setStyleSheet("\n"
"    /* ///////////////////////////////////////////////////////////////\n"
"    QToolTip\n"
"    /////////////////////////////////////////////////////////////// */\n"
"    QToolTip {\n"
"        background: rgba(23,23,23, 150);\n"
"        border: 1px solid rgb(52,121,71);\n"
"        border-radius: 5px;\n"
"        padding:4px;\n"
"        text-align: left;\n"
"        color: rgb(52,121,71);\n"
"    }\n"
"    \n"
"\n"
"        QSlider::handle:vertical:hover {\n"
"image:url(:/newPrefix/stresshomie.png);\n"
"}")
        self.stress_slider.setMaximum(10)
        self.stress_slider.setInvertedAppearance(False)
        self.stress_slider.setInvertedControls(False)
        self.stress_slider.setTickPosition(QtWidgets.QSlider.TickPosition.NoTicks)
        self.stress_slider.setObjectName("stress_slider")
        self.gridLayout_2.addWidget(self.stress_slider, 1, 1, 1, 1)
        self.pain_slider = QtWidgets.QSlider(parent=self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pain_slider.sizePolicy().hasHeightForWidth())
        self.pain_slider.setSizePolicy(sizePolicy)
        self.pain_slider.setStatusTip("")
        self.pain_slider.setStyleSheet("\n"
"    /* ///////////////////////////////////////////////////////////////\n"
"    QToolTip\n"
"    /////////////////////////////////////////////////////////////// */\n"
"    QToolTip {\n"
"        background: rgba(23,23,23, 150);\n"
"        border: 1px solid rgb(52,121,71);\n"
"        border-radius: 5px;\n"
"        padding:4px;\n"
"        text-align: left;\n"
"        color: rgb(52,121,71);\n"
"    }\n"
"    \n"
"\n"
"        QSlider::handle:vertical:hover {\n"
"image:url(:/newPrefix/painhomie.png);\n"
"}")
        self.pain_slider.setMaximum(10)
        self.pain_slider.setInvertedAppearance(False)
        self.pain_slider.setInvertedControls(False)
        self.pain_slider.setTickPosition(QtWidgets.QSlider.TickPosition.NoTicks)
        self.pain_slider.setObjectName("pain_slider")
        self.gridLayout_2.addWidget(self.pain_slider, 1, 2, 1, 1)
        self.pain_spinbox = QtWidgets.QSpinBox(parent=self.frame)
        self.pain_spinbox.setAutoFillBackground(False)
        self.pain_spinbox.setStyleSheet("\n"
"    /* ///////////////////////////////////////////////////////////////\n"
"    QToolTip\n"
"    /////////////////////////////////////////////////////////////// */\n"
"    QToolTip {\n"
"        background: rgba(23,23,23, 150);\n"
"        border: 1px solid rgb(90,208,122);\n"
"        border-radius: 5px;\n"
"        padding:4px;\n"
"        text-align: left;\n"
"        color: rgb(90,208,122);\n"
"    }\n"
"\n"
"    ")
        self.pain_spinbox.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.pain_spinbox.setButtonSymbols(QtWidgets.QAbstractSpinBox.ButtonSymbols.NoButtons)
        self.pain_spinbox.setMaximum(10)
        self.pain_spinbox.setObjectName("pain_spinbox")
        self.gridLayout_2.addWidget(self.pain_spinbox, 0, 2, 1, 1)
        self.buttonBox_2 = QtWidgets.QDialogButtonBox(parent=self.frame)
        self.buttonBox_2.setStyleSheet("QFrame {background: transparent;}\n"
"QPushButton {\n"
"padding:4px 8px 4px 8px;\n"
"color:rgb(89, 176, 99);\n"
"border-radius:5px;\n"
"background:transparent;\n"
"min-width:40px;\n"
"max-width:40px;\n"
"\n"
"}\n"
"QPushButton:hover {\n"
"margin-top:1px;\n"
"margin-left:1px;\n"
"color:rgb(139, 206, 149);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    margin-top:0px;\n"
"    margin-left:0px;\n"
"}")
        self.buttonBox_2.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.buttonBox_2.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.No|QtWidgets.QDialogButtonBox.StandardButton.Ok)
        self.buttonBox_2.setObjectName("buttonBox_2")
        self.gridLayout_2.addWidget(self.buttonBox_2, 2, 0, 1, 4)
        self.gridLayout_3.addWidget(self.frame, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.csprContainer, 0, 0, 1, 1)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.rage_slider.setToolTip(_translate("Dialog", "<html><head/><body><p>Rage</p></body></html>"))
        self.calm_spinbox.setToolTip(_translate("Dialog", "<html><head/><body><p>Calm</p></body></html>"))
        self.stress_spinbox.setToolTip(_translate("Dialog", "<html><head/><body><p>Stress</p></body></html>"))
        self.rage_spinbox.setToolTip(_translate("Dialog", "<html><head/><body><p>Rage</p></body></html>"))
        self.pain_spinbox.setToolTip(_translate("Dialog", "<html><head/><body><p>Pain</p></body></html>"))
