# Form implementation generated from reading ui file 'mood_dialog.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(242, 292)
        Dialog.setStyleSheet("QWidget {\n"
"    font: 12pt \"Helvetica\";\n"
"    background:#121212;\n"
"    color:rgb(255,255,255);\n"
"}\n"
"\n"
"/* /////////////////////////////////////////////////////////////////////////////\n"
"QTimeEdit, QDoubleSpinBox, QSpinBox\n"
"///////////////////////////////////////////////////////////////////////////// */\n"
"QDoubleSpinBox,\n"
"QSpinBox {\n"
"    border:none;\n"
"}\n"
"")
        self.gridLayout = QtWidgets.QGridLayout(Dialog)
        self.gridLayout.setObjectName("gridLayout")
        self.mmdmContainer = QtWidgets.QFrame(parent=Dialog)
        self.mmdmContainer.setStyleSheet("\n"
"/* /////////////////////////////////////////////////////////////////////////////\n"
"QSlider\n"
"///////////////////////////////////////////////////////////////////////////// */\n"
"QSlider::groove:vertical {\n"
"border-radius: 5px;\n"
"width: 30px;\n"
"margin: 0px;\n"
"background:rgb(22, 24, 29);\n"
"}\n"
"\n"
"QSlider::groove:vertical:hover {\n"
"background: rgba(233,123,111,0.25);\n"
"}\n"
"\n"
"QSlider::handle:vertical {\n"
"background: rgb(233,123,111);\n"
"height: 25px;\n"
"width: 40px;\n"
"margin: 0px -9px 0px -9px;\n"
"border-radius:5px;\n"
"}\n"
"\n"
"QSlider::add-page:vertical {\n"
"background:transparent;\n"
"}\n"
"\n"
"QSlider::handle:vertical:hover {\n"
"background-color: rgb(255,163,151);\n"
"}\n"
"\n"
"QSlider::handle:vertical:pressed {\n"
"background-color:rgb(188,78,66);\n"
"}\n"
"\n"
"\n"
"\n"
"\n"
"/* ///////////////////////////////////////////////////////////////\n"
"WEFE SLIDERS\n"
"/////////////////////////////////////////////////////////////// */\n"
"\n"
"#wellbeing_slider::handle:vertical {background:rgb(142,150,255);}\n"
"#wellbeing_slider::handle:vertical:hover {background:rgb(182,190,255);}\n"
"#wellbeing_slider::handle:vertical:pressed {background:rgb(92,100,205);}\n"
"#wellbeing_slider::groove:vertical:hover {background:rgba(142,150,255,0.25);}\n"
"#wellbeing_slider::groove:vertical {background:rgba(142,150,255,0.15);}\n"
"\n"
"        \n"
"\n"
"/* ///////////////////////////////////////////////////////////////\n"
"QSlider Colors\n"
"/////////////////////////////////////////////////////////////// */\n"
"\n"
"#energy_slider::handle:vertical {background:rgb(64,68,132);}\n"
"#energy_slider::handle:vertical:hover {background:rgb(104,108,172);}\n"
"#energy_slider::handle:vertical:pressed {background:rgb(44,58,122);}\n"
"#energy_slider::groove:vertical:hover {background:rgba(64,68,132,0.25);}\n"
"#energy_slider::groove:vertical {background:rgba(64,68,132,0.15);}\n"
"\n"
"        \n"
"\n"
"/* ///////////////////////////////////////////////////////////////\n"
"QSlider Colors\n"
"/////////////////////////////////////////////////////////////// */\n"
"\n"
"#excite_slider::handle:vertical {\n"
"    background:rgb(113,119,203);\n"
"}\n"
"#excite_slider::handle:vertical:hover {\n"
"    background:rgb(153,159,243);\n"
"}\n"
"#excite_slider::handle:vertical:pressed {\n"
"    background:rgb(64,68,132);\n"
"}\n"
"#excite_slider::groove:vertical:hover {\n"
"    background:rgba(113,119,203,0.25);\n"
"}\n"
"#excite_slider::groove:vertical {    \n"
"    background:rgba(113,119,203,0.15);\n"
"}\n"
"\n"
"#focus_slider::handle:vertical {background:rgb(87,90,156);}\n"
"#focus_slider::handle:vertical:hover {background:rgb(127,130,196);}\n"
"#focus_slider::handle:vertical:pressed {background:rgb(64,68,132);}\n"
"#focus_slider::groove:vertical:hover {background:rgba(87,90,156,0.25);}\n"
"#focus_slider::groove:vertical {background:rgba(87,90,156,0.15);}\n"
"\n"
"        \n"
"\n"
"\n"
"/* ///////////////////////////////////////////////////////////////\n"
"CSPR\n"
"/////////////////////////////////////////////////////////////// */\n"
"\n"
"#calm_slider::handle:vertical {background:rgb(52,121,71);}\n"
"#calm_slider::handle:vertical:hover {background:rgb(92,161,111);}\n"
"#calm_slider::handle:vertical:pressed {background:rgb(32,100,51);}\n"
"#calm_slider::groove:vertical:hover {background:rgba(52,121,71,0.25);}\n"
"#calm_slider::groove:vertical {background:rgba(52,121,71,0.15);}\n"
"\n"
"#stress_slider::handle:vertical {background:rgb(77,176,104);}\n"
"#stress_slider::handle:vertical:hover {background:rgb(117,216,144);}\n"
"#stress_slider::handle:vertical:pressed {background:rgb(52,121,71);}\n"
"#stress_slider::groove:vertical:hover {background:rgba(77,176,104,0.25);}\n"
"#stress_slider::groove:vertical {background:rgba(77,176,104,0.15);}\n"
"\n"
"        \n"
"#pain_slider::handle:vertical {background:rgb(90,207,122);}\n"
"#pain_slider::handle:vertical:hover {background:rgb(130,247,162);}\n"
"#pain_slider::handle:vertical:pressed {background:rgb(52,121,71);}\n"
"#pain_slider::groove:vertical:hover {background:rgba(90,207,122,0.25);}\n"
"#pain_slider::groove:vertical {background:rgba(90,207,122,0.15);}\n"
"\n"
"#rage_slider::handle:vertical {background:rgb(123,241,155);}\n"
"#rage_slider::handle:vertical:hover {background:rgb(163,255,195);}\n"
"#rage_slider::handle:vertical:pressed  {background:rgb(52,121,71);}\n"
"#rage_slider::groove:vertical:hover {background:rgba(123,241,155,0.25);}\n"
"#rage_slider::groove:vertical {background:rgba(123,241,155,0.15);}\n"
"\n"
"        \n"
"\n"
"/* ///////////////////////////////////////////////////////////////\n"
"MMDMR\n"
"/////////////////////////////////////////////////////////////// */\n"
"#mood_slider::handle:vertical {background:rgb(109,92,128);}\n"
"#mood_slider::handle:vertical:hover {background:rgb(149,132,168);}\n"
"#mood_slider::handle:vertical:pressed {background:rgb(89,72,100);}\n"
"#mood_slider::groove:vertical:hover {background:rgba(109,92,128,0.25);}\n"
"#mood_slider::groove:vertical {background:rgba(109,92,128,0.15);}\n"
"\n"
"#mania_slider::handle:vertical {background:rgb(135,114,159);}\n"
"#mania_slider::handle:vertical:hover {background:rgb(175,154,199);}\n"
"#mania_slider::handle:vertical:pressed {background:rgb(109,92,128);}\n"
"#mania_slider::groove:vertical:hover {background:rgba(135,114,159,0.25);}\n"
"#mania_slider::groove:vertical {background:rgba(135,114,159,0.15);}\n"
"\n"
"#depression_slider::handle:vertical {background:rgb(174,146,204);}\n"
"#depression_slider::handle:vertical:hover {background:rgb(214,186,244);}\n"
"#depression_slider::handle:vertical:pressed {background:rgb(109,92,128);}\n"
"#depression_slider::groove:vertical:hover {background:rgba(174,146,204,0.25);}\n"
"#depression_slider::groove:vertical {background:rgba(174,146,204,0.15);}\n"
"\n"
"#mixed_risk_slider::handle:vertical {background:rgb(211,191,232);}\n"
"#mixed_risk_slider::handle:vertical:hover {background:rgb(251,231,255);}\n"
"#mixed_risk_slider::handle:vertical:pressed {background:rgb(109,92,128);}\n"
"#mixed_risk_slider::groove:vertical:hover {background:rgba(211,191,232,0.25);}\n"
"#mixed_risk_slider::groove:vertical {background:rgba(211,191,232,0.15);}\n"
"\n"
"        \n"
"        \n"
"/*\n"
"QSpinBoxes\n"
"*/\n"
"\n"
"/*CSPR*/\n"
"#calm_spinbox {color:rgb(52,121,71);}\n"
"#calm_spinbox:hover {color: rgb(112,181,131);}\n"
"#calm_spinbox:focus {color: rgb(82,151,101);}\n"
"\n"
"#stress_spinbox {color:rgb(73,167,98);}\n"
"#stress_spinbox:hover {color: rgb(133,227,158);}\n"
"#stress_spinbox:focus {color: rgb(103,197,128);}\n"
"\n"
"#pain_spinbox{color:rgb(90,208,122);}\n"
"#pain_spinbox:hover {color: rgb(150,255,182);}\n"
"#pain_spinbox:focus {color: rgb(120,238,152);}\n"
"\n"
"#rage_spinbox {color:rgb(123,241,155);}\n"
"#rage_spinbox:hover {color: rgb(183,255,215);}\n"
"#rage_spinbox:focus {color: rgb(153,255,185);}    \n"
"\n"
"/*WEFE*/\n"
"#excite_spinbox{color:rgb(96,103,171);}\n"
"#excite_spinbox:hover {color: rgb(156,163,231);}\n"
"#excite_spinbox:focus {color: rgb(126,133,201);}\n"
"  \n"
"#wellbeing_spinbox {color:rgb(96,103,171);}\n"
"#wellbeing_spinbox:hover {color: rgb(156,163,231);}\n"
"#wellbeing_spinbox:focus {color: rgb(126,133,201);}\n"
"\n"
"#focus_spinbox {color:rgb(96,103,171);}\n"
"#focus_spinbox:hover {color: rgb(156,163,231);}\n"
"#focus_spinbox:focus {color: rgb(126,133,201);}\n"
"\n"
"#energy_spinbox {color:rgb(96,103,171);}\n"
"#energy_spinbox:hover {color: rgb(156,163,231);}\n"
"#energy_spinbox:focus {color: rgb(126,133,201);}\n"
"\n"
"/*MMDMR*/\n"
"#mood {color:rgb(109,92,128);}\n"
"#mood:hover {color: rgb(169,152,188);}\n"
"#mood:focus {color: rgb(139,122,158);}\n"
"\n"
"#mania {color:rgb(135,114,159);}\n"
"#mania:hover {color: rgb(195,174,219);}\n"
"#mania:focus {color: rgb(165,144,189);}\n"
"    \n"
"#depression {color:rgb(174,146,204);}\n"
"#depression:hover {color: rgb(234,206,255);}\n"
"#depression:focus {color: rgb(204,176,234);}\n"
"    \n"
"\n"
"#mixed_risk {color:rgb(211,191,232);}\n"
"#mixed_risk:hover {color: rgb(255,251,255);}\n"
"#mixed_risk:focus {color: rgb(241,221,255);}")
        self.mmdmContainer.setObjectName("mmdmContainer")
        self.gridLayout_119 = QtWidgets.QGridLayout(self.mmdmContainer)
        self.gridLayout_119.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_119.setHorizontalSpacing(0)
        self.gridLayout_119.setVerticalSpacing(8)
        self.gridLayout_119.setObjectName("gridLayout_119")
        self.depression_slider = QtWidgets.QSlider(parent=self.mmdmContainer)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.depression_slider.sizePolicy().hasHeightForWidth())
        self.depression_slider.setSizePolicy(sizePolicy)
        self.depression_slider.setStyleSheet("QSlider::handle:vertical:hover {\n"
"    image: url(:/newPrefix/depressiony.png);\n"
"}\n"
"QSlider::handle:vertical:pressed {\n"
"    image: url(:/newPrefix/depressiony.png);\n"
"}")
        self.depression_slider.setMaximum(10)
        self.depression_slider.setInvertedAppearance(False)
        self.depression_slider.setInvertedControls(False)
        self.depression_slider.setTickPosition(QtWidgets.QSlider.TickPosition.NoTicks)
        self.depression_slider.setObjectName("depression_slider")
        self.gridLayout_119.addWidget(self.depression_slider, 1, 2, 2, 1)
        self.mixed_risk_slider = QtWidgets.QSlider(parent=self.mmdmContainer)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mixed_risk_slider.sizePolicy().hasHeightForWidth())
        self.mixed_risk_slider.setSizePolicy(sizePolicy)
        self.mixed_risk_slider.setStyleSheet("QSlider::handle:vertical:hover {\n"
"image:url(:/newPrefix/mixin.png);\n"
"}")
        self.mixed_risk_slider.setMaximum(10)
        self.mixed_risk_slider.setInvertedAppearance(False)
        self.mixed_risk_slider.setInvertedControls(False)
        self.mixed_risk_slider.setTickPosition(QtWidgets.QSlider.TickPosition.NoTicks)
        self.mixed_risk_slider.setObjectName("mixed_risk_slider")
        self.gridLayout_119.addWidget(self.mixed_risk_slider, 1, 3, 2, 1)
        self.mood_slider = QtWidgets.QSlider(parent=self.mmdmContainer)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mood_slider.sizePolicy().hasHeightForWidth())
        self.mood_slider.setSizePolicy(sizePolicy)
        self.mood_slider.setStyleSheet("QSlider::handle:vertical:hover {image:url(:/newPrefix/moofy.png);}")
        self.mood_slider.setMaximum(10)
        self.mood_slider.setInvertedAppearance(False)
        self.mood_slider.setInvertedControls(False)
        self.mood_slider.setTickPosition(QtWidgets.QSlider.TickPosition.NoTicks)
        self.mood_slider.setObjectName("mood_slider")
        self.gridLayout_119.addWidget(self.mood_slider, 1, 0, 2, 1)
        self.mixed_risk = QtWidgets.QSpinBox(parent=self.mmdmContainer)
        self.mixed_risk.setStyleSheet("")
        self.mixed_risk.setFrame(False)
        self.mixed_risk.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.mixed_risk.setButtonSymbols(QtWidgets.QAbstractSpinBox.ButtonSymbols.NoButtons)
        self.mixed_risk.setMaximum(10)
        self.mixed_risk.setObjectName("mixed_risk")
        self.gridLayout_119.addWidget(self.mixed_risk, 0, 3, 1, 1)
        self.mania_slider = QtWidgets.QSlider(parent=self.mmdmContainer)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mania_slider.sizePolicy().hasHeightForWidth())
        self.mania_slider.setSizePolicy(sizePolicy)
        self.mania_slider.setStyleSheet("QSlider::handle:vertical:hover {\n"
"image:url(:/newPrefix/manias.png);\n"
"}")
        self.mania_slider.setMaximum(10)
        self.mania_slider.setInvertedAppearance(False)
        self.mania_slider.setInvertedControls(False)
        self.mania_slider.setTickPosition(QtWidgets.QSlider.TickPosition.NoTicks)
        self.mania_slider.setObjectName("mania_slider")
        self.gridLayout_119.addWidget(self.mania_slider, 1, 1, 2, 1)
        self.depression = QtWidgets.QSpinBox(parent=self.mmdmContainer)
        self.depression.setStyleSheet("")
        self.depression.setFrame(False)
        self.depression.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.depression.setButtonSymbols(QtWidgets.QAbstractSpinBox.ButtonSymbols.NoButtons)
        self.depression.setMaximum(10)
        self.depression.setObjectName("depression")
        self.gridLayout_119.addWidget(self.depression, 0, 2, 1, 1)
        self.mood = QtWidgets.QSpinBox(parent=self.mmdmContainer)
        self.mood.setStyleSheet("\n"
"    /* ///////////////////////////////////////////////////////////////\n"
"    QToolTip\n"
"    /////////////////////////////////////////////////////////////// */\n"
"    QToolTip {\n"
"        background: rgba(23,23,23, 150);\n"
"        border: 1px solid rgb(220,78,53);\n"
"        border-radius: 5px;\n"
"        padding:4px;\n"
"        text-align: left;\n"
"        color: rgb(220,78,53);\n"
"    }\n"
"\n"
"")
        self.mood.setFrame(False)
        self.mood.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.mood.setButtonSymbols(QtWidgets.QAbstractSpinBox.ButtonSymbols.NoButtons)
        self.mood.setMaximum(10)
        self.mood.setObjectName("mood")
        self.gridLayout_119.addWidget(self.mood, 0, 0, 1, 1)
        self.mania = QtWidgets.QSpinBox(parent=self.mmdmContainer)
        self.mania.setStyleSheet("")
        self.mania.setFrame(False)
        self.mania.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.mania.setButtonSymbols(QtWidgets.QAbstractSpinBox.ButtonSymbols.NoButtons)
        self.mania.setMaximum(10)
        self.mania.setObjectName("mania")
        self.gridLayout_119.addWidget(self.mania, 0, 1, 1, 1)
        self.buttonBox = QtWidgets.QDialogButtonBox(parent=self.mmdmContainer)
        self.buttonBox.setStyleSheet("QFrame {background: transparent;}\n"
"QPushButton {\n"
"padding:4px 8px 4px 8px;\n"
"color:rgb(210, 191, 234);\n"
"border-radius:5px;\n"
"background:transparent;\n"
"min-width:40px;\n"
"max-width:40px;\n"
"\n"
"}\n"
"QPushButton:hover {\n"
"margin-top:1px;\n"
"margin-left:1px;\n"
"color:rgb(250, 231, 255);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    margin-top:0px;\n"
"    margin-left:0px;\n"
"}")
        self.buttonBox.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.No|QtWidgets.QDialogButtonBox.StandardButton.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayout_119.addWidget(self.buttonBox, 3, 0, 1, 4)
        self.gridLayout.addWidget(self.mmdmContainer, 0, 0, 1, 1)

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept) # type: ignore
        self.buttonBox.rejected.connect(Dialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.depression_slider.setToolTip(_translate("Dialog", "<html><head/><body><p>DEPRESSION</p></body></html>"))
        self.mixed_risk_slider.setToolTip(_translate("Dialog", "<html><head/><body><p>MIXED RISK</p></body></html>"))
        self.mood_slider.setToolTip(_translate("Dialog", "<html><head/><body><p>MOOD</p></body></html>"))
        self.mixed_risk.setToolTip(_translate("Dialog", "<html><head/><body><p>MIXED RISK</p></body></html>"))
        self.mania_slider.setToolTip(_translate("Dialog", "<html><head/><body><p>MANIA</p></body></html>"))
        self.depression.setToolTip(_translate("Dialog", "<html><head/><body><p>DEPRESSION</p></body></html>"))
        self.mood.setToolTip(_translate("Dialog", "<html><head/><body><p>MOOD</p></body></html>"))
        self.mania.setToolTip(_translate("Dialog", "<html><head/><body><p>MANIA</p></body></html>"))
