# Form implementation generated from reading ui file 'exercise_ui.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(204, 214)
        Dialog.setStyleSheet("\n"
"QWidget {\n"
"    font: 11pt \"Helvetica\";\n"
"    border-radius:10px;\n"
"background:#121212;\n"
"\n"
"}\n"
"QFrame {\n"
"border-radius:10px;background:#121212;\n"
"}\n"
"\n"
"/* //////////////////////////////////////////////////////////////\n"
"QSlider HORIZONTALALALALALAL\n"
"////////////////////////////////////////////////////////////// */\n"
"QSlider:horizontal {\n"
"    background:transparent;\n"
"    border:none;\n"
"    min-height:18px;\n"
"}\n"
"QSlider::groove:horizontal {\n"
"    border-radius: 8px;\n"
"    height: 16px;\n"
"    margin: 0px;\n"
"    background:rgb(22, 22, 22);\n"
"    }\n"
"\n"
"QSlider::groove:horizontal:hover {\n"
"    background: rgb(38, 38, 38);\n"
"}\n"
"QSlider::handle:horizontal {\n"
"    background: rgb(255, 255, 255);\n"
"    height: 16px;\n"
"    width: 16px;\n"
"    margin: 0px;\n"
"    border-radius:8px;\n"
"}\n"
"QSlider::sub-page:horizontal {\n"
"    background:transparent;\n"
"}\n"
"QSlider::handle:horizontal:hover {\n"
"    background-color: white;\n"
"}\n"
"QSlider::handle:horizontal:pressed {\n"
"    background-color:white;\n"
"}\n"
"/* ///////////////////////////////////////////////////////////////\n"
"QSpinBox\n"
"/////////////////////////////////////////////////////////////// */\n"
"QSpinBox {color:rgb(143,148,255);}\n"
"QSpinBox:hover {color: rgb(203,208,255);}\n"
"QSpinBox:focus {color: rgb(173,178,255);}\n"
"\n"
"\n"
"/* ////////////////////////////////////////////////////////////////////////////////\n"
"QLabel\n"
"//////////////////////////////////////////////////////////////////////////////// */\n"
"QLabel {\n"
"    background:transparent;\n"
"    color:rgb(143,148,255);\n"
"}\n"
"QLabel:hover {\n"
"    color: rgb(203,208,255);\n"
"}\n"
"\n"
"/* ////////////////////////////////////////////////////////////////////////////////\n"
"QLineEdit\n"
"//////////////////////////////////////////////////////////////////////////////// */\n"
"QLineEdit {    font-size:11pt;\n"
"    border:none;\n"
"    color:rgb(143,148,255);\n"
"}\n"
"\n"
"QLineEdit:hover {\n"
"    color:rgb(173,178,255);\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    color:rgb(123,128,235);\n"
"}\n"
"\n"
"QDateEdit,\n"
"QTimeEdit {    font-size:11pt;\n"
"    border:none;\n"
"    color:rgb(143,148,255);\n"
"}\n"
"\n"
"QDateEdit:hover,\n"
"QTimeEdit:hover {\n"
"    color:rgb(173,178,255);\n"
"}\n"
"\n"
"QDateEdit:focus,\n"
"QTimeEdit:focus {\n"
"    color:rgb(123,128,235);\n"
"}\n"
"/* ////////////////////////////////////////////////////////////////////////////////\n"
"QPushButton\n"
"//////////////////////////////////////////////////////////////////////////////// */\n"
"QPushButton {\n"
"    min-width:65px;\n"
"    border:none;\n"
"    color:rgb(143,148,255);\n"
"}\n"
"QPushButton:hover {\n"
"    color:rgb(173,178,255);\n"
"}\n"
"QPushButton:pressed {\n"
"    color: #666;\n"
"}\n"
"\n"
"QPushButton {\n"
"    color:rgb(123,128,235);\n"
"}\n"
"\n"
"QPushButton:focus {\n"
"    color:#fff;\n"
"}\n"
"\n"
"/* ///////////////////////////////////////////////////////////////\n"
"QSlider Colors\n"
"/////////////////////////////////////////////////////////////// */\n"
"\n"
"QSlider::handle:horizontal {background:rgb(143,148,255);}\n"
"QSlider::handle:horizontal:hover {background:rgb(173,178,255);}\n"
"QSlider::handle:horizontal:pressed {background:rgb(123,128,235);}\n"
"QSlider::groove:horizontal:hover {background:rgba(143,148,255,0.25);}\n"
"QSlider::groove:horizontal {background:rgba(143,148,255,0.15);}\n"
"\n"
"\n"
"\n"
"")
        self.gridLayout_2 = QtWidgets.QGridLayout(Dialog)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.frame = QtWidgets.QFrame(parent=Dialog)
        self.frame.setStyleSheet("QFrame {background:#121212}")
        self.frame.setObjectName("frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout.setObjectName("verticalLayout")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.label_3 = QtWidgets.QLabel(parent=self.frame)
        self.label_3.setStyleSheet("\n"
"/* ///////////////////////////////////////////////////////////////\n"
"QLabel\n"
"/////////////////////////////////////////////////////////////// */\n"
"QLabel {\n"
"font-weight:300;\n"
"    color: rgb(132, 127, 239);\n"
"}\n"
"QLabel:hover {\n"
"    color: rgb(162, 157, 255);\n"
"}\n"
"")
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.frame_2 = QtWidgets.QFrame(parent=self.frame)
        self.frame_2.setObjectName("frame_2")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.frame_2)
        self.gridLayout_5.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.label_4 = QtWidgets.QLabel(parent=self.frame_2)
        self.label_4.setStyleSheet("\n"
"/* ///////////////////////////////////////////////////////////////\n"
"QLabel\n"
"/////////////////////////////////////////////////////////////// */\n"
"QLabel {\n"
"font-weight:300;\n"
"    color: rgb(132, 127, 239);\n"
"}\n"
"QLabel:hover {\n"
"    color: rgb(162, 157, 255);\n"
"}\n"
"")
        self.label_4.setObjectName("label_4")
        self.gridLayout_5.addWidget(self.label_4, 1, 0, 1, 2)
        self.intensity_slider = QtWidgets.QSlider(parent=self.frame_2)
        self.intensity_slider.setStyleSheet("\n"
"/* ///////////////////////////////////////////////////////////////\n"
"QSlider Colors\n"
"/////////////////////////////////////////////////////////////// */\n"
"\n"
"QSlider::handle:horizontal {background:rgb(132,127,239);}\n"
"QSlider::handle:horizontal:hover {background:rgb(162,157,255);}\n"
"QSlider::handle:horizontal:pressed {background:rgb(112,107,219);}\n"
"QSlider::groove:horizontal:hover {background:rgba(132,127,239,0.25);}\n"
"QSlider::groove:horizontal {background:rgba(132,127,239,0.15);}\n"
"")
        self.intensity_slider.setMinimum(0)
        self.intensity_slider.setMaximum(10)
        self.intensity_slider.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.intensity_slider.setObjectName("intensity_slider")
        self.gridLayout_5.addWidget(self.intensity_slider, 4, 0, 1, 4)
        self.length_of_exercise = QtWidgets.QSpinBox(parent=self.frame_2)
        self.length_of_exercise.setStyleSheet("\n"
"/* ///////////////////////////////////////////////////////////////\n"
"QSpinBox\n"
"/////////////////////////////////////////////////////////////// */\n"
"QSpinBox {color:rgb(132,127,239);}\n"
"QSpinBox:hover {color: rgb(192,187,255);}\n"
"QSpinBox:focus {color: rgb(162,157,255);}\n"
"")
        self.length_of_exercise.setFrame(False)
        self.length_of_exercise.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.length_of_exercise.setButtonSymbols(QtWidgets.QAbstractSpinBox.ButtonSymbols.NoButtons)
        self.length_of_exercise.setSuffix("")
        self.length_of_exercise.setMinimum(0)
        self.length_of_exercise.setMaximum(10)
        self.length_of_exercise.setObjectName("length_of_exercise")
        self.gridLayout_5.addWidget(self.length_of_exercise, 1, 2, 1, 2, QtCore.Qt.AlignmentFlag.AlignRight)
        self.sleep_quality_lbl_4 = QtWidgets.QLabel(parent=self.frame_2)
        self.sleep_quality_lbl_4.setStyleSheet("\n"
"/* ///////////////////////////////////////////////////////////////\n"
"QLabel\n"
"/////////////////////////////////////////////////////////////// */\n"
"QLabel {\n"
"font-weight:300;\n"
"    color: rgb(132, 127, 239);\n"
"}\n"
"QLabel:hover {\n"
"    color: rgb(162, 157, 255);\n"
"}\n"
"")
        self.sleep_quality_lbl_4.setObjectName("sleep_quality_lbl_4")
        self.gridLayout_5.addWidget(self.sleep_quality_lbl_4, 3, 0, 1, 3)
        self.exercise_type_input = QtWidgets.QLineEdit(parent=self.frame_2)
        self.exercise_type_input.setStyleSheet("\n"
"/* ///////////////////////////////////////////////////////////////\n"
"QTimeEdit\n"
"/////////////////////////////////////////////////////////////// */\n"
"QLineEdit {color:rgb(132,127,239);border:none;}\n"
"QLineEdit:hover {color: rgb(152,147,255);border:none;}\n"
"QLineEdit:focus {color: rgb(172,167,255);border:none;}\n"
"")
        self.exercise_type_input.setText("")
        self.exercise_type_input.setFrame(False)
        self.exercise_type_input.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.exercise_type_input.setObjectName("exercise_type_input")
        self.gridLayout_5.addWidget(self.exercise_type_input, 0, 0, 1, 4)
        self.intensity_spinbox = QtWidgets.QSpinBox(parent=self.frame_2)
        self.intensity_spinbox.setStyleSheet("\n"
"/* ///////////////////////////////////////////////////////////////\n"
"QSpinBox\n"
"/////////////////////////////////////////////////////////////// */\n"
"QSpinBox {color:rgb(132,127,239);}\n"
"QSpinBox:hover {color: rgb(192,187,255);}\n"
"QSpinBox:focus {color: rgb(162,157,255);}\n"
"")
        self.intensity_spinbox.setFrame(False)
        self.intensity_spinbox.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.intensity_spinbox.setButtonSymbols(QtWidgets.QAbstractSpinBox.ButtonSymbols.NoButtons)
        self.intensity_spinbox.setSuffix("")
        self.intensity_spinbox.setMinimum(0)
        self.intensity_spinbox.setMaximum(10)
        self.intensity_spinbox.setObjectName("intensity_spinbox")
        self.gridLayout_5.addWidget(self.intensity_spinbox, 3, 3, 1, 1)
        self.verticalLayout.addWidget(self.frame_2)
        self.frame_3 = QtWidgets.QFrame(parent=self.frame)
        self.frame_3.setObjectName("frame_3")
        self.gridLayout = QtWidgets.QGridLayout(self.frame_3)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setVerticalSpacing(4)
        self.gridLayout.setObjectName("gridLayout")
        self.effort_slider = QtWidgets.QSlider(parent=self.frame_3)
        self.effort_slider.setStyleSheet("\n"
"/* ///////////////////////////////////////////////////////////////\n"
"QSlider Colors\n"
"/////////////////////////////////////////////////////////////// */\n"
"\n"
"QSlider::handle:horizontal {background:rgb(132,127,239);}\n"
"QSlider::handle:horizontal:hover {background:rgb(162,157,255);}\n"
"QSlider::handle:horizontal:pressed {background:rgb(112,107,219);}\n"
"QSlider::groove:horizontal:hover {background:rgba(132,127,239,0.25);}\n"
"QSlider::groove:horizontal {background:rgba(132,127,239,0.15);}\n"
"")
        self.effort_slider.setMinimum(0)
        self.effort_slider.setMaximum(10)
        self.effort_slider.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.effort_slider.setObjectName("effort_slider")
        self.gridLayout.addWidget(self.effort_slider, 1, 0, 1, 4)
        self.effort_spinbox = QtWidgets.QSpinBox(parent=self.frame_3)
        self.effort_spinbox.setStyleSheet("\n"
"/* ///////////////////////////////////////////////////////////////\n"
"QSpinBox\n"
"/////////////////////////////////////////////////////////////// */\n"
"QSpinBox {color:rgb(132,127,239);}\n"
"QSpinBox:hover {color: rgb(192,187,255);}\n"
"QSpinBox:focus {color: rgb(162,157,255);}\n"
"")
        self.effort_spinbox.setFrame(False)
        self.effort_spinbox.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.effort_spinbox.setButtonSymbols(QtWidgets.QAbstractSpinBox.ButtonSymbols.NoButtons)
        self.effort_spinbox.setSuffix("")
        self.effort_spinbox.setMinimum(0)
        self.effort_spinbox.setMaximum(10)
        self.effort_spinbox.setObjectName("effort_spinbox")
        self.gridLayout.addWidget(self.effort_spinbox, 0, 3, 1, 1)
        self.sleep_quality_lbl = QtWidgets.QLabel(parent=self.frame_3)
        self.sleep_quality_lbl.setStyleSheet("\n"
"/* ///////////////////////////////////////////////////////////////\n"
"QLabel\n"
"/////////////////////////////////////////////////////////////// */\n"
"QLabel {\n"
"font-weight:300;\n"
"    color: rgb(132, 127, 239);\n"
"}\n"
"QLabel:hover {\n"
"    color: rgb(162, 157, 255);\n"
"}\n"
"")
        self.sleep_quality_lbl.setObjectName("sleep_quality_lbl")
        self.gridLayout.addWidget(self.sleep_quality_lbl, 0, 0, 1, 3)
        self.verticalLayout.addWidget(self.frame_3)
        self.buttonBox = QtWidgets.QDialogButtonBox(parent=self.frame)
        self.buttonBox.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.No|QtWidgets.QDialogButtonBox.StandardButton.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.gridLayout_2.addWidget(self.frame, 0, 0, 1, 1)

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept) # type: ignore
        self.buttonBox.rejected.connect(Dialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        Dialog.setTabOrder(self.exercise_type_input, self.length_of_exercise)
        Dialog.setTabOrder(self.length_of_exercise, self.intensity_spinbox)
        Dialog.setTabOrder(self.intensity_spinbox, self.effort_spinbox)
        Dialog.setTabOrder(self.effort_spinbox, self.effort_slider)
        Dialog.setTabOrder(self.effort_slider, self.intensity_slider)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label_3.setText(_translate("Dialog", "exercise type"))
        self.label_4.setText(_translate("Dialog", "exercise length"))
        self.sleep_quality_lbl_4.setText(_translate("Dialog", "effort"))
        self.exercise_type_input.setPlaceholderText(_translate("Dialog", "yoga . hitting shit?"))
        self.sleep_quality_lbl.setText(_translate("Dialog", "intensity"))
