# Form implementation generated from reading ui file 'exercise_ui.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(167, 205)
        MainWindow.setStyleSheet("QWidget {\n"
"    font: 11pt \"Helvetica\";\n"
"    background:#121212;\n"
"    color:rgb(255,255,255);\n"
"}\n"
"/* /////////////////////////////////////////////////////////////////////////////////////////\n"
"TheMinds Labels\n"
"///////////////////////////////////////////////////////////////////////////////////// */\n"
"\n"
"\n"
"\n"
"/* /////////////////////////////////////////////////////////////////////////////\n"
"QTextEdit\n"
"///////////////////////////////////////////////////////////////////////////// */\n"
"QTextEdit {\n"
"    border:none;\n"
"    font-size: 12pt;\n"
"}\n"
"\n"
"\n"
"/* ///////////////////////////////////////////////////////////////\n"
"QToolTip\n"
"/////////////////////////////////////////////////////////////// */\n"
"QToolTip {\n"
"    background: rgba(23,23,23, 150);\n"
"    border: 1px solid rgb(132,127,239);\n"
"    border-radius: 5px; \n"
"    padding:4px; \n"
"    text-align: left;\n"
"    color: rgb(132,127,239);\n"
"}\n"
"\n"
"\n"
"/* /////////////////////////////////////////////////////////////////////////////\n"
"QTimeEdit, QDoubleSpinBox, QSpinBox\n"
"///////////////////////////////////////////////////////////////////////////// */\n"
"QDoubleSpinBox,\n"
"QSpinBox {\n"
"    border:none;\n"
"    font-size:11pt;\n"
"}\n"
"\n"
"/* /////////////////////////////////////////////////////////////////////////////\n"
"QLabel\n"
"///////////////////////////////////////////////////////////////////////////// */\n"
"QLabel {\n"
"    background:transparent;\n"
"}\n"
"/* /////////////////////////////////////////////////////////////////////////////\n"
"QCheckBox\n"
"///////////////////////////////////////////////////////////////////////////// */\n"
"QCheckBox::indicator {\n"
"    font-weight:bold;\n"
"    background-color: transparent;\n"
"    border: 2px solid rgb(33,143,109);\n"
"    border-radius: 6px;\n"
"    width: 8px;\n"
"    height: 8px;\n"
"    margin-left:8px;\n"
"    margin-right:8px;\n"
"}\n"
"QCheckBox::indicator:hover {\n"
"    border: 2px solid white;\n"
"}\n"
"QCheckBox::indicator:checked {\n"
"    background: rgb(33,143,109);\n"
"    border: 2px solid rgb(33,143,109);\n"
"}\n"
"\n"
"/* //////////////////////////////////////////////////////////////\n"
"QSlider HORIZONTALALALALALAL\n"
"////////////////////////////////////////////////////////////// */\n"
"QSlider:horizontal {\n"
"    background:transparent;\n"
"    border:none;\n"
"    min-height:18px;\n"
"}\n"
"QSlider::groove:horizontal {\n"
"    border-radius: 8px;\n"
"    height: 16px;\n"
"    margin: 0px;\n"
"    background:rgb(22, 22, 22);\n"
"    }\n"
"\n"
"QSlider::groove:horizontal:hover {\n"
"    background: rgb(38, 38, 38);\n"
"}\n"
"QSlider::handle:horizontal {\n"
"    background: rgb(255, 255, 255);\n"
"    height: 16px;\n"
"    width: 16px;\n"
"    margin: 0px;\n"
"    border-radius:8px;\n"
"}\n"
"QSlider::sub-page:horizontal {\n"
"    background:transparent;\n"
"}\n"
"QSlider::handle:horizontal:hover {\n"
"    background-color: white;\n"
"}\n"
"QSlider::handle:horizontal:pressed {\n"
"    background-color:white;\n"
"}\n"
"\n"
"/* /////////////////////////////////////////////////////////////////////////////\n"
"Time/DateEdit\n"
"///////////////////////////////////////////////////////////////////////////// */\n"
"QTimeEdit,\n"
"QDateEdit {\n"
"    background-color: transparent;\n"
"    border:None;\n"
"font-size:11pt;\n"
"}\n"
"\n"
"/* //////////////////////////////////////////////////////////////////////////////\n"
"QTableView\n"
"////////////////////////////////////////////////////////////////////////////// */\n"
"QTableView {\n"
"    background-color: transparent;\n"
"    alternate-background-color: rgb(101, 147, 128);\n"
"    selection-background-color: #7e57c2;\n"
"    gridline-color: rgb(90, 90, 90);color:rgb(245,245,245);\n"
"}\n"
"\n"
"QTableView::item {\n"
"    padding: 1px;\n"
"    background:rgb(216,79,79);\n"
"}\n"
"QTableView::item:selected {\n"
"    color: #fff;\n"
"    background:rgb(23, 23, 23);\n"
"}\n"
"\n"
"\n"
"/* ////////////////////////////////////////////////////////////////////////////////////////////////\n"
"                                    QScrollBar\n"
"//////////////////////////////////////////////////////////////////////////////////////////////// */\n"
"QScrollBar:horizontal {border: none;background:transparent;height: 12px;margin: 0px 10px 0px 10px;border-radius: 3px;}\n"
"QScrollBar::handle:horizontal {background: rgb(35,35,37);min-width:24px;border-radius: 4px}\n"
"QScrollBar::add-line:horizontal {border: none;background: transparent;width: 20px;border-top-right-radius: 4px;border-bottom-right-radius: 4px;subcontrol-position: right;subcontrol-origin: margin;}\n"
"QScrollBar::sub-line:horizontal {border: none;background: transparent;width: 20px;border-top-left-radius: 4px;border-bottom-left-radius: 4px;subcontrol-position: left;subcontrol-origin: margin;}\n"
"QScrollBar::up-arrow:horizontal, QScrollBar::down-arrow:horizontal {background: none;}\n"
"QScrollBar::add-page:horizontal, QScrollBar::sub-page:horizontal {background: transparent;}\n"
"QScrollBar:vertical {border: none;background-color:transparent;width: 12px;margin: 10px 0px 10px 0px;border-radius: 4px;}\n"
"QScrollBar::handle:vertical {background: rgb(35,35,37);min-height: 12px;border-radius: 4px}\n"
"QScrollBar::add-line:vertical {border: none;background: transparent;height: 20px;border-bottom-left-radius: 4px;border-bottom-right-radius: 4px;subcontrol-position: bottom;subcontrol-origin: margin;}\n"
"QScrollBar::sub-line:vertical {border: none;background: transparent;height: 20px;border-top-left-radius: 4px;border-top-right-radius: 4px;subcontrol-position: top;subcontrol-origin: margin;}\n"
"QScrollBar::up-arrow:vertical, QScrollBar::down-arrow:vertical {background: none;}\n"
"QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical {background: transparent;}\n"
"\n"
"\n"
"\n"
"")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setContentsMargins(8, 8, 8, 8)
        self.gridLayout_2.setSpacing(0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.frame = QtWidgets.QFrame(parent=self.centralwidget)
        self.frame.setObjectName("frame")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.frame)
        self.gridLayout_4.setObjectName("gridLayout_4")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.gridLayout_4.addItem(spacerItem, 0, 0, 1, 1)
        self.frame1 = QtWidgets.QFrame(parent=self.frame)
        self.frame1.setObjectName("frame1")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame1)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_3 = QtWidgets.QLabel(parent=self.frame1)
        self.label_3.setStyleSheet("\n"
"/* ///////////////////////////////////////////////////////////////\n"
"QLabel\n"
"/////////////////////////////////////////////////////////////// */\n"
"QLabel {\n"
"font-weight:300;\n"
"    color: rgb(132, 127, 239);\n"
"}\n"
"QLabel:hover {\n"
"    color: rgb(162, 157, 255);\n"
"}\n"
"")
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.frame_2 = QtWidgets.QFrame(parent=self.frame1)
        self.frame_2.setObjectName("frame_2")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.frame_2)
        self.gridLayout_5.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.label_4 = QtWidgets.QLabel(parent=self.frame_2)
        self.label_4.setStyleSheet("\n"
"/* ///////////////////////////////////////////////////////////////\n"
"QLabel\n"
"/////////////////////////////////////////////////////////////// */\n"
"QLabel {\n"
"font-weight:300;\n"
"    color: rgb(132, 127, 239);\n"
"}\n"
"QLabel:hover {\n"
"    color: rgb(162, 157, 255);\n"
"}\n"
"")
        self.label_4.setObjectName("label_4")
        self.gridLayout_5.addWidget(self.label_4, 1, 0, 1, 2)
        self.intensity_slider = QtWidgets.QSlider(parent=self.frame_2)
        self.intensity_slider.setStyleSheet("\n"
"/* ///////////////////////////////////////////////////////////////\n"
"QSlider Colors\n"
"/////////////////////////////////////////////////////////////// */\n"
"\n"
"QSlider::handle:horizontal {background:rgb(132,127,239);}\n"
"QSlider::handle:horizontal:hover {background:rgb(162,157,255);}\n"
"QSlider::handle:horizontal:pressed {background:rgb(112,107,219);}\n"
"QSlider::groove:horizontal:hover {background:rgba(132,127,239,0.25);}\n"
"QSlider::groove:horizontal {background:rgba(132,127,239,0.15);}\n"
"")
        self.intensity_slider.setMinimum(0)
        self.intensity_slider.setMaximum(10)
        self.intensity_slider.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.intensity_slider.setObjectName("intensity_slider")
        self.gridLayout_5.addWidget(self.intensity_slider, 4, 0, 1, 4)
        self.length_of_exercise = QtWidgets.QSpinBox(parent=self.frame_2)
        self.length_of_exercise.setStyleSheet("\n"
"/* ///////////////////////////////////////////////////////////////\n"
"QSpinBox\n"
"/////////////////////////////////////////////////////////////// */\n"
"QSpinBox {color:rgb(132,127,239);}\n"
"QSpinBox:hover {color: rgb(192,187,255);}\n"
"QSpinBox:focus {color: rgb(162,157,255);}\n"
"")
        self.length_of_exercise.setFrame(False)
        self.length_of_exercise.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.length_of_exercise.setButtonSymbols(QtWidgets.QAbstractSpinBox.ButtonSymbols.NoButtons)
        self.length_of_exercise.setSuffix("")
        self.length_of_exercise.setMinimum(0)
        self.length_of_exercise.setMaximum(10)
        self.length_of_exercise.setObjectName("length_of_exercise")
        self.gridLayout_5.addWidget(self.length_of_exercise, 1, 2, 1, 2, QtCore.Qt.AlignmentFlag.AlignRight)
        self.sleep_quality_lbl_4 = QtWidgets.QLabel(parent=self.frame_2)
        self.sleep_quality_lbl_4.setStyleSheet("\n"
"/* ///////////////////////////////////////////////////////////////\n"
"QLabel\n"
"/////////////////////////////////////////////////////////////// */\n"
"QLabel {\n"
"font-weight:300;\n"
"    color: rgb(132, 127, 239);\n"
"}\n"
"QLabel:hover {\n"
"    color: rgb(162, 157, 255);\n"
"}\n"
"")
        self.sleep_quality_lbl_4.setObjectName("sleep_quality_lbl_4")
        self.gridLayout_5.addWidget(self.sleep_quality_lbl_4, 3, 0, 1, 3)
        self.exercise_type_input = QtWidgets.QLineEdit(parent=self.frame_2)
        self.exercise_type_input.setStyleSheet("\n"
"/* ///////////////////////////////////////////////////////////////\n"
"QTimeEdit\n"
"/////////////////////////////////////////////////////////////// */\n"
"QLineEdit {color:rgb(132,127,239);border:none;}\n"
"QLineEdit:hover {color: rgb(152,147,255);border:none;}\n"
"QLineEdit:focus {color: rgb(172,167,255);border:none;}\n"
"")
        self.exercise_type_input.setText("")
        self.exercise_type_input.setFrame(False)
        self.exercise_type_input.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.exercise_type_input.setObjectName("exercise_type_input")
        self.gridLayout_5.addWidget(self.exercise_type_input, 0, 0, 1, 4)
        self.intensity_spinbox = QtWidgets.QSpinBox(parent=self.frame_2)
        self.intensity_spinbox.setStyleSheet("\n"
"/* ///////////////////////////////////////////////////////////////\n"
"QSpinBox\n"
"/////////////////////////////////////////////////////////////// */\n"
"QSpinBox {color:rgb(132,127,239);}\n"
"QSpinBox:hover {color: rgb(192,187,255);}\n"
"QSpinBox:focus {color: rgb(162,157,255);}\n"
"")
        self.intensity_spinbox.setFrame(False)
        self.intensity_spinbox.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.intensity_spinbox.setButtonSymbols(QtWidgets.QAbstractSpinBox.ButtonSymbols.NoButtons)
        self.intensity_spinbox.setSuffix("")
        self.intensity_spinbox.setMinimum(0)
        self.intensity_spinbox.setMaximum(10)
        self.intensity_spinbox.setObjectName("intensity_spinbox")
        self.gridLayout_5.addWidget(self.intensity_spinbox, 3, 3, 1, 1)
        self.verticalLayout.addWidget(self.frame_2)
        self.frame2 = QtWidgets.QFrame(parent=self.frame1)
        self.frame2.setObjectName("frame2")
        self.gridLayout = QtWidgets.QGridLayout(self.frame2)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.sleep_quality_lbl = QtWidgets.QLabel(parent=self.frame2)
        self.sleep_quality_lbl.setStyleSheet("\n"
"/* ///////////////////////////////////////////////////////////////\n"
"QLabel\n"
"/////////////////////////////////////////////////////////////// */\n"
"QLabel {\n"
"font-weight:300;\n"
"    color: rgb(132, 127, 239);\n"
"}\n"
"QLabel:hover {\n"
"    color: rgb(162, 157, 255);\n"
"}\n"
"")
        self.sleep_quality_lbl.setObjectName("sleep_quality_lbl")
        self.gridLayout.addWidget(self.sleep_quality_lbl, 0, 0, 1, 3)
        self.effort_slider = QtWidgets.QSlider(parent=self.frame2)
        self.effort_slider.setStyleSheet("\n"
"/* ///////////////////////////////////////////////////////////////\n"
"QSlider Colors\n"
"/////////////////////////////////////////////////////////////// */\n"
"\n"
"QSlider::handle:horizontal {background:rgb(132,127,239);}\n"
"QSlider::handle:horizontal:hover {background:rgb(162,157,255);}\n"
"QSlider::handle:horizontal:pressed {background:rgb(112,107,219);}\n"
"QSlider::groove:horizontal:hover {background:rgba(132,127,239,0.25);}\n"
"QSlider::groove:horizontal {background:rgba(132,127,239,0.15);}\n"
"")
        self.effort_slider.setMinimum(0)
        self.effort_slider.setMaximum(10)
        self.effort_slider.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.effort_slider.setObjectName("effort_slider")
        self.gridLayout.addWidget(self.effort_slider, 1, 0, 1, 4)
        self.effort_spinbox = QtWidgets.QSpinBox(parent=self.frame2)
        self.effort_spinbox.setStyleSheet("\n"
"/* ///////////////////////////////////////////////////////////////\n"
"QSpinBox\n"
"/////////////////////////////////////////////////////////////// */\n"
"QSpinBox {color:rgb(132,127,239);}\n"
"QSpinBox:hover {color: rgb(192,187,255);}\n"
"QSpinBox:focus {color: rgb(162,157,255);}\n"
"")
        self.effort_spinbox.setFrame(False)
        self.effort_spinbox.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.effort_spinbox.setButtonSymbols(QtWidgets.QAbstractSpinBox.ButtonSymbols.NoButtons)
        self.effort_spinbox.setSuffix("")
        self.effort_spinbox.setMinimum(0)
        self.effort_spinbox.setMaximum(10)
        self.effort_spinbox.setObjectName("effort_spinbox")
        self.gridLayout.addWidget(self.effort_spinbox, 0, 3, 1, 1)
        self.verticalLayout.addWidget(self.frame2)
        self.gridLayout_4.addWidget(self.frame1, 1, 0, 1, 1)
        self.gridLayout_2.addWidget(self.frame, 0, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.gridLayout_2.addItem(spacerItem1, 1, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 167, 16))
        self.menubar.setObjectName("menubar")
        self.menuSleepMo = QtWidgets.QMenu(parent=self.menubar)
        self.menuSleepMo.setObjectName("menuSleepMo")
        self.menuData = QtWidgets.QMenu(parent=self.menubar)
        self.menuData.setObjectName("menuData")
        MainWindow.setMenuBar(self.menubar)
        self.action_show_input_page = QtGui.QAction(parent=MainWindow)
        self.action_show_input_page.setObjectName("action_show_input_page")
        self.action_show_data_page = QtGui.QAction(parent=MainWindow)
        self.action_show_data_page.setObjectName("action_show_data_page")
        self.action_commit_data = QtGui.QAction(parent=MainWindow)
        self.action_commit_data.setObjectName("action_commit_data")
        self.action_delete_table_row = QtGui.QAction(parent=MainWindow)
        self.action_delete_table_row.setObjectName("action_delete_table_row")
        self.action_total_hours = QtGui.QAction(parent=MainWindow)
        self.action_total_hours.setObjectName("action_total_hours")
        self.actionMinimize = QtGui.QAction(parent=MainWindow)
        self.actionMinimize.setObjectName("actionMinimize")
        self.actionMaximize = QtGui.QAction(parent=MainWindow)
        self.actionMaximize.setObjectName("actionMaximize")
        self.menuSleepMo.addAction(self.action_show_input_page)
        self.menuSleepMo.addAction(self.action_show_data_page)
        self.menuSleepMo.addAction(self.action_commit_data)
        self.menuSleepMo.addAction(self.action_delete_table_row)
        self.menuSleepMo.addAction(self.action_total_hours)
        self.menuSleepMo.addAction(self.actionMinimize)
        self.menuSleepMo.addAction(self.actionMaximize)
        self.menubar.addAction(self.menuSleepMo.menuAction())
        self.menubar.addAction(self.menuData.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_3.setText(_translate("MainWindow", "exercise type"))
        self.label_4.setText(_translate("MainWindow", "exercise length"))
        self.sleep_quality_lbl_4.setText(_translate("MainWindow", "effort"))
        self.exercise_type_input.setPlaceholderText(_translate("MainWindow", "yoga . hitting shit?"))
        self.sleep_quality_lbl.setText(_translate("MainWindow", "intensity"))
        self.menuSleepMo.setTitle(_translate("MainWindow", "SleepMo"))
        self.menuData.setTitle(_translate("MainWindow", "Data"))
        self.action_show_input_page.setText(_translate("MainWindow", "Show Input"))
        self.action_show_input_page.setShortcut(_translate("MainWindow", "Ctrl+1"))
        self.action_show_data_page.setText(_translate("MainWindow", "Show Data"))
        self.action_show_data_page.setShortcut(_translate("MainWindow", "Ctrl+2"))
        self.action_commit_data.setText(_translate("MainWindow", "Commit Data"))
        self.action_commit_data.setShortcut(_translate("MainWindow", "Ctrl+Shift+C"))
        self.action_delete_table_row.setText(_translate("MainWindow", "Delete Selected Row"))
        self.action_delete_table_row.setShortcut(_translate("MainWindow", "Ctrl+Alt+D"))
        self.action_total_hours.setText(_translate("MainWindow", "Calculate Hours Slept"))
        self.action_total_hours.setShortcut(_translate("MainWindow", "Ctrl+3"))
        self.actionMinimize.setText(_translate("MainWindow", "Minimize"))
        self.actionMinimize.setShortcut(_translate("MainWindow", "Alt+M"))
        self.actionMaximize.setText(_translate("MainWindow", "Maximize"))
        self.actionMaximize.setShortcut(_translate("MainWindow", "Ctrl+M"))
